package jasmin.parser_;
//----------------------------------------------------
// The following code was generated by Java(tm) CUP v0.9d
// Fri May 07 07:55:04 MSD 2010
//----------------------------------------------------


/** JavaCup generated class containing symbol constants. */
public interface sym {
  /* terminals */
  int FROM = 27;
  int DSIGNATURE = 19;
  int SYNTHETIC = 59;
  int OUTER = 37;
  int DCLASS = 3;
  int DVAR = 13;
  int DSUPER = 10;
  int SIGNATURE = 29;
  int ENUM = 55;
  int INVISIBLE = 39;
  int INNER = 36;
  int Insn = 68;
  int TABLESWITCH = 61;
  int STACK = 30;
  int Int = 69;
  int LOOKUPSWITCH = 60;
  int TRANSIENT = 52;
  int PROTECTED = 48;
  int FINAL = 44;
  int DSOURCE = 11;
  int EQ = 63;
  int CLASS = 34;
  int DDEBUG = 17;
  int ABSTRACT = 43;
  int DINTERFACE = 15;
  int NATIVE = 46;
  int DTHROWS = 12;
  int USE = 42;
  int INTERFACE = 45;
  int VARARGS = 57;
  int DDEPRECATED = 22;
  int DSET = 9;
  int DFIELD = 5;
  int VISIBLE = 38;
  int DLIMIT = 6;
  int PUBLIC = 49;
  int DEND = 4;
  int DENCLOSING = 18;
  int DMETHOD = 8;
  int STRICT = 58;
  int DANNOTATION = 24;
  int EOF = 0;
  int DEFAULT = 62;
  int VISIBLEPARAM = 40;
  int OFFSET = 31;
  int DATTRIBUTE = 21;
  int IS = 26;
  int METHOD = 28;
  int DBYTECODE = 16;
  int error = 1;
  int SYNCHRONIZED = 51;
  int Word = 67;
  int SEP = 64;
  int ANNOTATION = 54;
  int BRIDGE = 56;
  int COLON = 65;
  int USING = 25;
  int DLINE = 7;
  int FIELD = 33;
  int DCATCH = 2;
  int VOLATILE = 53;
  int LOCALS = 32;
  int DINNER = 23;
  int Relative = 71;
  int INVISIBLEPARAM = 41;
  int DIMPLEMENTS = 14;
  int DSTACK = 20;
  int PRIVATE = 47;
  int TO = 35;
  int STATIC = 50;
  int Str = 66;
  int Num = 70;
}

